### ISSUE TITLE
Can we use this for our meetups tracker functionality

### ISSUE THREAD

**Issue by JonDevOps** [w3develops/w3develops#123]
https://www.openstreetmap.org/#map=4/38.01/-95.84 . I saw it here at: https://24pullrequests.com/events

**Comment by maks-ushakov** [comment]
Can you explain what you exactly want?

Do you want to use 24pullrequests.com API for meetups or make own API with openstreetmap API MAP?

**Comment by JonDevOps** [comment]
I want to make our own api with openstreetmap. I do not want to do anything with the 24pull requests api.

**Comment by JonDevOps** [comment]
https://cloud.google.com/maps-platform/#_ga=2.208571547.840655586.1543290839-141150877.1543290839
