### ISSUE TITLE
Bunch of not-actually-minified files.  ex: agency.min.css

### ISSUE THREAD

**Issue by waterlgndx** [w3develops/w3develops#143]
We need to either copy agency.min.css to agency.css and generate a minified file of that, or do away with minified files that we often edit.  If we opt to generate minified files we need to automate the process on here.  This will make it more difficult to test changes because everytime someone makes a change to `whatever.css` they'll need to change the `<link>` tag so it refers to `whatever.css` as opposed to the `whatever.min.css`.  Then before commiting the developer will need to change it back to refer to the `whatever.min.css` and the automated tool will minify `whatever.css` (thereby updating the `*.min.*` file).  I think for the complexity it adds and the lack of performance savings it would be best to rid ourselves of the minified file altogether and refer instead to the .css file.

**Comment by JonDevOps** [comment]
I totally agree. lets do away with minified. Let's delete it.

**Comment by JonDevOps** [comment]
Thank you Ben! I'm going to dive down the css rabbit hole soon and delete as much of the agency.css file as we do not need, it will be fun and i hope i will learn alot...and clean up all that extra unused code lingering in there.

**Comment by JonDevOps** [comment]
Thanks for being on top of this Ben. I didnt actually know what you meant or how to do this but I am setting gulp up for this right now, and I will also set gulp up to minimize not only agency which its defaulted to minimize, but also the w3develops.css and w3develops.js files and also the html_util.js and any other files possible to minimize.
