### ISSUE TITLE
Can anyone answer this question?

### ISSUE THREAD

**Issue by JonDevOps** [w3develops/w3develops#145]
https://www.quora.com/unanswered/How-do-I-add-node_modules-and-package-lock-json-files-to-my-directory

**Comment by RA9** [comment]
Check quora and see my suggestion

**Comment by suli-g** [comment]
From [This Stackoverflow answer](https://stackoverflow.com/questions/30140112/how-do-i-hide-certain-files-from-the-sidebar-in-visual-studio-code#answer-30142299), We find that you can go to:
`File > Preferences > Settings`
Then, in the search bar, type: `files:exclude`

From the `Files:exclude` list, remove `**/*.lock` and `**/node_modules`
