### ISSUE TITLE
Center the text in the footer

### ISSUE THREAD

**Issue by JonDevOps** [w3develops/w3develops#147]
We need the text in the footer to be perfectly centered.

**Comment by adamosimpson21** [comment]
I can take up this issue :) Let me make a mock-up to help with exactly what is needed. Is this something like what'd you want?

![image](https://user-images.githubusercontent.com/13780256/49492382-e4663680-f80c-11e8-952a-e124f29aee54.png)

**Comment by JonDevOps** [comment]
It looks great. Would you take out the social links, privacy policy, and the terms of use please. I would love it if " © 2018 w3Develops, made with love for a better web." was all on one line after that. Then it would be perfect!

**Comment by adamosimpson21** [comment]
So, you'd like it to only be the copyright? 

1. 
![image](https://user-images.githubusercontent.com/13780256/49546321-cb08cd00-f894-11e8-9306-ee35dc572e4c.png)
 or
2. 
![image](https://user-images.githubusercontent.com/13780256/49546367-e542ab00-f894-11e8-911f-fe9050f23b25.png)

**Comment by JonDevOps** [comment]
Yea that is perfect, thank you man, send that pr when you are ready and we will review. Nice skills dude.

**Comment by adamosimpson21** [comment]
It's giving me a permission denied warning? The steps I've taken:
1. cloned this repo
2. create new branch (footerFix)
3. made changes
4. commit changes
5. git push origin footerFix
6. put in my github credentials (username+pass)
 => returns 403 error

**Comment by JonDevOps** [comment]
On  GitHUb go to the "Pull Request" tab and try making submitting your changes there.

**Comment by adamosimpson21** [comment]
It seems like my branch doesn't exist on that page. I'm trying to create the branch on my fork (which I should have access to) and then merge from there, but I'm having some version control issues since I pulled from this repository

**Comment by adamosimpson21** [comment]
Ok, pull request made :)
