### ISSUE TITLE
Incorporate COPA for teens messenger in terms of service

### ISSUE THREAD

**Issue by JonDevOps** [w3develops/w3develops#153]
Make a proper terms of service children under 13 need parental permission. Every violation is 16k fine

**Comment by sadetavarez** [comment]
Hello,

May I work on this issue? And if so, where should I put the terms of service?

**Comment by JonDevOps** [comment]
Excellent! If you create a blank .html with simply the terms of service, we will review and then add the styling and such.

**Comment by sadetavarez** [comment]
Ok, I've added the HTML code of the terms to the Wiki section of the repository.

**Comment by JonDevOps** [comment]
Ok if you send the pull request we will begin the review.

**Comment by sadetavarez** [comment]
Done.

**Comment by JonDevOps** [comment]
update: still not complete
