### ISSUE TITLE
add this http to https redirect

### ISSUE THREAD

**Issue by JonDevOps** [w3develops/w3develops#160]
delete the old code redirect merthod https://www.namecheap.com/support/knowledgebase/article.aspx/9821/38/redirect-to-https-on-apache

**Comment by waterlgndx** [comment]
I think you'll need to make the change on Apache unless someone else has access too

**Comment by JonDevOps** [comment]
You are right.

**Comment by waterlgndx** [comment]
Just let us know when that's done and we can remove it here.
