### ISSUE TITLE
add a forum section to the community tab and link it to reddit

### ISSUE THREAD

**Issue by JonDevOps** [w3develops/w3develops#189]

**Comment by Bhupesh-V** [comment]
Hey @JonDevOps 
is [this](https://www.reddit.com/user/w3develops/) of reddit correct?

**Comment by JonDevOps** [comment]
No this one is https://www.reddit.com/r/w3Develops/

**Comment by JonDevOps** [comment]
im going to close this because we are going to scrap this idea and make a legit forum

**Comment by Bhupesh-V** [comment]
I guess discourse would be good choice , what do you think?

bhupeshv.me
