### ISSUE TITLE
make a webpage for our documentation possibly with docusaurus 

### ISSUE THREAD

**Issue by JonDevOps** [w3develops/w3develops#223]
80% of the top 100 github projects do not use readmes to explain their documentation instead they have dedicated websites for this.  So we will do the same and add our documentation to a subdomain.  And example of a website that does this is reactjs.org. An idea i have for the subdomain name can be w3develops.org/documentation. I want to see if we should incorporate docusaurus into the the mix for doing this.

**Comment by waterlgndx** [comment]
I mean certainly could refactor information that is more documentary in nature to a docs folder in the repo.  I don't know if that is an outdated convention but I figured I'd throw it out there.  I don't suspect our website itself to be terribly interesting as a contribution to the open source community; however, any projects that later run the show from the back end may be good for this.  Or non domain specific front end (i.e. reusable non branded material) could also be a valuable contribution.  The website itself is a community driven website and as such is open source.  

Source code standards should probably be defined either in a GitHub wiki or site wiki/documentation.  It probably should be referenced somewhere people would look (doc folder or contributor file).

I'm curious about learning more about why documentation would be out of the repository though.  I suppose it's not actually the source but it's still important info in most cases...

**Comment by JonDevOps** [comment]
It would not be out of the repo, it would just have html pages to go with it.

**Comment by JonDevOps** [comment]
Here is a intro from facebook https://www.youtube.com/watch?v=QcGJsf6mgZE&t=258s
