### ISSUE TITLE
Make a hacker games link section and user profile links

### ISSUE THREAD

**Issue by JonDevOps** [w3develops/w3develops#29]
Enable users to share score and view other users profiles and scores and usernames for individual hacker game websites. Also github buttons so users can upload github profile links, enable progress to automatically be uploaded & shown on the profile for each activity someone completes on github, codefights, freecodecamp, medium, etc

**Comment by jbull328** [comment]
Seems like a cool Idea... I tried to implement something similar with FreeCodeCamp and found it tricky, to automate. You could have a form where users manual input their link to their latest post, code push, freeCodeCamp solution. Github should have a way to do it easily though

**Comment by RA9** [comment]
The idea seem cool  but to implement it is like a work in progress
