### ISSUE TITLE
The jumbotron needsto be mobile responsive

### ISSUE THREAD

**Issue by JonDevOps** [w3develops/w3develops#31]
For some reason the jumbotron image cuts out the screen instead of reducing size to fit screen. This must be fixed.

**Comment by abutler911** [comment]
The jumbotron is responsive now but the H1 and button need to be fixed. Also, the jumbotron needs spacing under the navbar

**Comment by JonDevOps** [comment]
No it's not ready yet. Gonna take a look into those now. What is wrong with h1 and which button are you referring to? I will also add space under the navbar. 

For what to needs to be fixed with the jumbotron .
