### ISSUE TITLE
allow users to link and sign in via 

### ISSUE THREAD

**Issue by JonDevOps** [w3develops/w3develops#37]
facebook, twitter, github. but require them to sign up with their email to confirm the account. **eMAIL REQUIRED**

**Comment by maks-ushakov** [comment]
sign in to what?

**Comment by JonDevOps** [comment]
User profiles that will help them keep track of people near by and there progress,  what theyre working on,  if they need help or want to collaborate or what their fcc curriculem lvl and github accounts and current profession and skills are. Also a way to message people,  maybe a gitter api,  idk, just a way to message each other. It would be cool if we had a 18+ side and a 0-17 side,  for user profiles.  I dont know the law for messaging systems and minors,  im pretty sure i should talk to a lawer or something for that...

**Comment by waterlgndx** [comment]
Do you mean like a way to link accounts or be able to sign up with (and login with) those accounts?  Could probably store links for each at first and later make the linking more intrinsic to the website?  Or maybe it's best to just do it right to begin with, I'm not sure what everyone's skill level is.

**Comment by JonDevOps** [comment]
I spoke with Quincy Larson about this on Twitter and he strongly recommended doing it right the first time and saving your own logins, but i want to do a combination of both. Where the user can partially sign up with facebook/github/google/twiiter/etc and then then have to complete registration by creating a username and password  for the site. The email and names and etc will be provided from when they linked their github/facebook/twitter/etc
