### ISSUE TITLE
find out how to make the h2 element under<h1> #w3develops </h1> change

### ISSUE THREAD

**Issue by JonDevOps** [w3develops/w3develops#38]
I want to have a library stored somewhere of small phrases like "a place for developers" "where developers collaborate" "learn+build=developer" "learn to build, build to learn" and other motivational monikers. What i want is for the text to change every time the page is refreshed.  When the text changes i want it to pick from the library one of the phrases stored there. I dont even know where to start with this one.

**Comment by abutler911** [comment]
I am sure it's not the prettiest way to write code but I took a stab at this and I think I got it working. I did a pull request with the changes.

**Comment by JonDevOps** [comment]
NICE! I had to do a double take when I noticed the text start changing. Impressive man!
