### ISSUE TITLE
add beta. so it reads beta.w3develops.org

### ISSUE THREAD

**Issue by JonDevOps** [w3develops/w3develops#62]
This is so we can work on the website without effecting the main website

**Comment by chompoo500ml** [comment]
Is this issue about how-to for dev workflow?

**Comment by waterlgndx** [comment]
usually what I do for this is add a beta folder and then add a redirect/virtual host for the beta.* subdomain.  I'm not sure what that would mean in terms of github pages though.  I guess the github way though would be to create a beta branch and see if you can use that as another github pages site and map beta.w3develops.org to that branch's page?

**Comment by waterlgndx** [comment]
I wonder if you can add a c name on a beta branch/folder for beta. ... I'll look into docs when I'm on the computer next.
