### ISSUE TITLE
FInd out why img-circle class doesn't work on 12.png

### ISSUE THREAD

**Issue by JonDevOps** [w3develops/w3develops#72]
Add a circle border to the image in the about section on the landing page

**Comment by waterlgndx** [comment]
It looks like the class was renamed.
https://github.com/w3develops/w3develops/blob/490e6e130f970c4e6769bdc2f1deef3670168107/index.html#L131
So it should be rounded-circle now.  See also:
https://www.w3schools.com/bootstrap4/bootstrap_images.asp
I'm kinda surprised that they didn't continue to support the older name for the class and go through a deprecation process like most libraries do.

**Comment by JonDevOps** [comment]
@waterlgndx I am going to try out the fix now, but strangely it works with the efault template image, so i do not understand why it does not work when i link to my new custom image itht the same demensions and name.

**Comment by JonDevOps** [comment]
@waterlgndx it works thank you bro!

**Comment by JonDevOps** [comment]
@waterlgndx solution worked flawlessly.

**Comment by waterlgndx** [comment]
Sweet I'm glad i could help.  I thought i had included that with the pull
request i submitted but apparently i didn't lol

**Comment by JonDevOps** [comment]
it is ok, you gave me some valuable experience and I appreciate that we can collaborate together bro :D
