### ISSUE TITLE
Replace bootstrap with css grid and flexbox

### ISSUE THREAD

**Issue by JonDevOps** [w3develops/w3develops#77]

**Comment by maks-ushakov** [comment]
But Duutstrap4 is based on flexbox.

**Comment by JonDevOps** [comment]
I see,  I didnt know that. But mainly what i would like to accomplish is: getting rid of all the extra and unused stylings created by the original user of the template and replace it with our own. I was thinking since thiis was orginally a bootstrap template that it would be better to use our own css. Maybe have someone do psd to html on it

**Comment by JonDevOps** [comment]
Gotcha thanks Mak. Ill close this down then.
