### ISSUE TITLE
Find out why back button does not let users leave the site on first click

### ISSUE THREAD

**Issue by JonDevOps** [w3develops/w3develops#79]
When clicking the back button to return from a previous page visited before visiting w3evelops.org, the back button does not return me to the previous page. Instead it is as if the page reloads itself. If i double click the back button it might work sometimes but sometimes i have to click it 9 or 10 times,, as if i am trying to beat the reload or something. I do not believe it ever goes to the previous page the first time clicked, instea it will just reload the page.

**Comment by waterlgndx** [comment]
That's an odd issue I'll look into it tomorrow unless someone beats me to it

**Comment by JonDevOps** [comment]
@waterlgndx I asked the question on Quora, check it out https://www.quora.com/Why-do-I-have-to-double-click-the-backspace-to-leave-my-website-Instead-of-clicking-the-back-button-once-like-on-most-websites

**Comment by waterlgndx** [comment]
Ah i see that answer makes sense.  There's usually a way to do it server side, maybe if the header included a redirect header the browser would skip the http site in the future?

**Comment by JonDevOps** [comment]
i will have to see if and or how that would be possible.

**Comment by waterlgndx** [comment]
https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by JonDevOps** [comment]
I will wrap my head around this. But i dont know if the cause is from redirection from http to https or.. from redirecting .com to .org . Idk javascript like that quite yet so idk which script might be the culprit.
