### ISSUE TITLE
find and delete all unnecessary files in the repository that are not directly contributing to the landing pages html css or javascrpt.

### ISSUE THREAD

**Issue by JonDevOps** [w3develops/w3develops#85]

**Comment by JonDevOps** [comment]
Do not delete necessary files such as cname or readme or liscence...etc...etc

**Comment by waterlgndx** [comment]
From what I can tell the files that are there are all needed.  Many of the less/gulp/json files are from the agency template you're using.  It's probable that you could design it down so it doesn't require agency and just use bootstrap.

If you remove the agency.css you lose backgrounds and layout of the site.
If you remove agency.js you lose the behavior of the navbar at the top.  (I'm thinking you'd probably lose other things too?)  You might want to play around and comment out the css/js and see if it's worth including agency.  I think bootstrap and/or css already has something to keep the navbar at the top but I'm not sure if you can have 2 different styles for the navbar like you can with agency.  Lemme know if you want a prototype without agency.

**Comment by JonDevOps** [comment]
@waterlgndx thank you for that detailed and informative explanation. I am definitely going to ply around with commenting out elements and files now, thank you again. Please do send me the prototype you are speaking of.

**Comment by waterlgndx** [comment]
I've been looking into this.  There seems to be a lot of files that aren't explicitly referenced but it seems they get loaded anyway.  I'm thinking the gulp and package files are supposed to be there while you're developing the site and then they can be removed after development is done?  (if you want to cut elements out that aren't in use.)

**Comment by JonDevOps** [comment]
Thank you waterlgndx for solving his issue!
